version: '3'

services:
  app:
    build: 
      context: .  # Use the current directory
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - coffee-shop-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./src/public:/usr/share/nginx/html # Optional, to serve static files
    ports:
      - "80:80"
    networks:
      - coffee-shop-network

networks:
  coffee-shop-network:
    driver: bridge
